##### 菜单
menu:
  主页: /
  归档: /archives
  关于: /about

#### 控件
widgets: 
- category
- tag
- links
- rss


#### RSS 
rss: /atom.xml 

#### 图片相关
imglogo:
  enable: false               ## 是否显示网站 logo
  src: img/logo.png        
favicon: img/favicon.ico     ## 网站图标    
apple_icon: img/logo.jpg   ## 苹果设备上的图标，背景不要透明
author_img: img/author.jpg   ## 网站底部的博主头像
banner_img: #img/banner.jpg   ## 博客顶部的图片

### 主题颜色
theme_color:
    theme: '#2ca6cb'    ##默认主题颜色为蓝色

close_aside: false      ##是否在文章页面自动关闭侧边栏

#### 首页相关
index:
  expand: true              ## 首页文章是否展开。默认为展开式，显示 Read More。
  excerpt_link: Read More    

#### 作者信息
author:
  intro_line1:  "Hello ,I'm Panda."    ## 网站底部的个人介绍
  intro_line2:  "This is my blog on Github"  
  weibo_verifier:  ## 微博秀的验证码
  tsina:           ## 用于微博秀和微博分享
  weibo:           ## 用于显示网站底部社交按钮，下同
  douban:         
  zhihu:  
  email:     
  twitter:   
  github:     
  facebook: 
  linkedin:   
  google_plus:   
  stackoverflow:  


#### 目录
toc:
  article: true   ## 是否在文章中显示目录
  aside: true     ## 是否在侧边栏显示目录

#### 友情链接
links:
  并发编程网: http://ifeve.com,高质量并发文章
  科学松鼠会: http://songshuhui.net,看科普文章这里就够了
  Coolshell: http://coolshell.cn,就是这么酷,楷模
  36Kr: http://36kr.com,关注互联网创业
  码农圈: https://coderq.com,一个面向程序员交流分享的新一代社区
  InfoQ: http://www.infoq.com/cn,高逼格技术社区
  阿里技术沙龙: http://club.alibabatech.org/index.htm,不错的技术沙龙
  美团技术博客: http://tech.meituan.com/archives


#### 评论
duoshuo_shortname: siye1982
disqus_shortname:  

#### 分享按钮
jiathis:
  enable: false   ## 默认使用主题内建分享
  id:    
  tsina: 
  
#### 网站统计
google_analytics:
  enable: false
  id:            ## google analytics ID.
  site:          ## 网站地址.
baidu_tongji:
  enable: false
  sitecode: 72577fbd30b666f35278832dfaee0280      ## 百度统计站点特征码
cnzz_tongji:
  enable: true
  siteid: 1255443286       ## CNZZ统计站点ID

#### 杂项
ShowCustomFont: true  
fancybox: true        
totop: true           

#### 自定义搜索
google_cse: 
  enable: true
  cx: "014646117278575712947:xe6pipn1zds"
baidu_search:    
  enable: false
  id:  
  site: 
tinysou_search:     ## http://tinysou.com/
  enable: false
  id: "45fd0c747128c27ff6d3"

